version: '3.8'
services:
  wss:
    build: ./server
    expose:
      - 8080
    environment:
      - PORT=5050
    ports:
      - 5050:5050

  client:
    build: ./client
    depends_on:
      - wss
    expose:
      - 5000
    environment:
      - PORT=5000
    ports:
      - 5000:5000
      
  ipfs:
    image: ipfs/go-ipfs
    ports:
      - 4001:4001
      - 5001:5001
      - 8080:8080
    volumes:
      - ./ipfs/data:/data/ipfs
      - ./ipfs/staging:/export