version: '3.8'
services:
  wss:
    build:
      context: ./server
    command: [ "dev" ]
    container_name: nft-server-dev
    expose:
      - 5050
    environment:
      - PORT=5050
    ports:
      - 5050:5050

  client:
    build: ./client
    container_name: nft-client-dev
    depends_on:
      - wss
    volumes:
      - ./client/public:/client/public
    environment:
      - PORT=5000
    ports:
      - 5000:5000

  ipfs:
    image: ipfs/go-ipfs
    ports:
      - 4001:4001
      - 5001:5001
      - 8080:8080
    volumes:
      - ./ipfs/data:/data/ipfs
      - ./ipfs/staging:/export
